#!/bin/bash -e

if [ $# -ne 1 ]; then
	echo "Must provide the name of the dist archive to package"
	exit 1
fi

rpmdev-setuptree
cp ${1}{,.asc} ~/rpmbuild/SOURCES
cp pcat.spec ~/rpmbuild/SPECS

rpmbuild -ba --sign ~/rpmbuild/SPECS/pcat.spec

cp ~/rpmbuild/RPMS/x86_64/pcat-*.rpm /data/pcat/package
cp ~/rpmbuild/SRPMS/pcat-*.src.rpm /data/pcat/package
